Repository unikraft/dynamic-apps, pull requests merged in 2023-10, with the labels that each got.

#86 Add curl into dynamic apps
  curl/curl
  curl/lib/x86_64-linux-gnu/libasn1.so.8
  curl/lib/x86_64-linux-gnu/libbrotlicommon.so.1
  curl/lib/x86_64-linux-gnu/libbrotlidec.so.1
  curl/lib/x86_64-linux-gnu/libc.so.6
  curl/lib/x86_64-linux-gnu/libcom_err.so.2
  curl/lib/x86_64-linux-gnu/libcrypt.so.1
  curl/lib/x86_64-linux-gnu/libcrypto.so.1.1
  curl/lib/x86_64-linux-gnu/libcurl.so.4
  curl/lib/x86_64-linux-gnu/libdl.so.2
  curl/lib/x86_64-linux-gnu/libffi.so.7
  curl/lib/x86_64-linux-gnu/libgmp.so.10
  curl/lib/x86_64-linux-gnu/libgnutls.so.30
  curl/lib/x86_64-linux-gnu/libgssapi.so.3
  curl/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
  curl/lib/x86_64-linux-gnu/libhcrypto.so.4
  curl/lib/x86_64-linux-gnu/libheimbase.so.1
  curl/lib/x86_64-linux-gnu/libheimntlm.so.0
  curl/lib/x86_64-linux-gnu/libhogweed.so.5
  curl/lib/x86_64-linux-gnu/libhx509.so.5
  curl/lib/x86_64-linux-gnu/libidn2.so.0
  curl/lib/x86_64-linux-gnu/libk5crypto.so.3
  curl/lib/x86_64-linux-gnu/libkeyutils.so.1
  curl/lib/x86_64-linux-gnu/libkrb5.so.26
  curl/lib/x86_64-linux-gnu/libkrb5.so.3
  curl/lib/x86_64-linux-gnu/libkrb5support.so.0
  curl/lib/x86_64-linux-gnu/liblber-2.4.so.2
  curl/lib/x86_64-linux-gnu/libldap_r-2.4.so.2
  curl/lib/x86_64-linux-gnu/libm.so.6
  curl/lib/x86_64-linux-gnu/libnettle.so.7
  curl/lib/x86_64-linux-gnu/libnghttp2.so.14
  curl/lib/x86_64-linux-gnu/libp11-kit.so.0
  curl/lib/x86_64-linux-gnu/libpsl.so.5
  curl/lib/x86_64-linux-gnu/libpthread.so.0
  curl/lib/x86_64-linux-gnu/libresolv.so.2
  curl/lib/x86_64-linux-gnu/libroken.so.18
  curl/lib/x86_64-linux-gnu/librtmp.so.1
  curl/lib/x86_64-linux-gnu/libsasl2.so.2
  curl/lib/x86_64-linux-gnu/libsqlite3.so.0
  curl/lib/x86_64-linux-gnu/libssh.so.4
  curl/lib/x86_64-linux-gnu/libssl.so.1.1
  curl/lib/x86_64-linux-gnu/libtasn1.so.6
  curl/lib/x86_64-linux-gnu/libunistring.so.2
  curl/lib/x86_64-linux-gnu/libwind.so.0
  curl/lib/x86_64-linux-gnu/libz.so.1
  curl/lib64/ld-linux-x86-64.so.2
Labels: enhancement

#101 README.md: Fix "dyamic" typo
  README.md
Labels: documentation, enhancement, kind/hackathon

#103 Add sed pre-built binary
  sed/README.md
  sed/input.txt
  sed/lib/x86_64-linux-gnu/libacl.so.1
  sed/lib/x86_64-linux-gnu/libc.so.6
  sed/lib/x86_64-linux-gnu/libpcre2-8.so.0
  sed/lib/x86_64-linux-gnu/libselinux.so.1
  sed/lib64/ld-linux-x86-64.so.2
  sed/usr/bin/sed
Labels: enhancement, kind/hackathon, hacktoberfest

#100 Add tar pre-built binary
  tar/README.md
  tar/lib/x86_64-linux-gnu/libacl.so.1
  tar/lib/x86_64-linux-gnu/libc.so.6
  tar/lib/x86_64-linux-gnu/libpcre2-8.so.0
  tar/lib/x86_64-linux-gnu/libselinux.so.1
  tar/lib64/ld-linux-x86-64.so.2
  tar/some.txt
  tar/usr/bin/tar
Labels: enhancement, kind/hackathon, hacktoberfest
